POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Volante",
  "preco": 55,
  "descricao": "uma breve descrição",
  "quantidadeEmEstoque": 20,
  "imagemUrl": "/images/volante.png"

}
