POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Limpador",
  "preco": 79.99,
  "descricao": "Limpador de parabrisa",
  "quantidadeEmEstoque": 2,
  "imagemUrl": "/images/limpador.png",
  "categoria": ""
}
